# Use postgres/example user/password credentials
# navigate to path
# docker compose up -d

version: '3.9'

services:

  db:
    image: postgres:16-alpine
    container_name: bd-postgres16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: rodrigofischer
      POSTGRES_PASSWORD: secret
    ports:
      - 5433:5432